spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: http://consumer-service-svc
          predicates:
            - Path=/consumer-service/**
          filters:
            # ignore path, no context-path defined in consumer-service
            - RewritePath=/consumer-service/(?<segment>.*), /$\{segment}
        - id: producer-service
          uri: http://producer-service-svc
          predicates:
            - Path=/producer-service/**
          filters:
            - RewritePath=/producer-service/(?<segment>.*), /$\{segment}