spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: http://consumer-service-svc
          predicates:
            - Path=/consumer-service/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            # ignore path, no context-path defined in consumer-service
            - RewritePath=/consumer-service/(?<segment>.*), /$\{segment}
        - id: producer-service
          uri: http://producer-service-svc
          predicates:
            - Path=/producer-service/**
          filters:
            # another config type for ignore path
            - StripPrefix=1
  redis:
    host: redis
    port: 6379