spring:
  application:
    name: gateway-api
  profiles:
    active: @profileActive@
  jmx:
    enabled: false

server:
  port: 9999


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health","info","gateway"]