spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/consumer-service/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            # ignore path, no context-path defined in consumer-service
            - RewritePath=/consumer-service/(?<segment>.*), /$\{segment}
        - id: producer-service
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/producer-service/**
          filters:
            # another config type for ignore path
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG