apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-dm
  namespace: springboot-kube
spec:
  selector:
    matchLabels:
      app: consumer-service
      version: V1.0.0
  replicas: 2
  # set the limit of history version
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 180
  template:
    metadata:
      labels:
        app: consumer-service
        version: V1.0.0
    spec:
      volumes:
        - name: private-secret-volume
          secret:
            secretName: private-secret
            # select which items to be mounted
            items:
              - key: privatekey
                path: privatekey.key
      containers:
        - name: consumer-service
          image: local-dtr.com/kube-consumer-service:Develop
          ports:
            - containerPort: 8081
              name: http
          # batch configmap ref
          envFrom:
            - configMapRef:
                name: consumer-configmap
          # single secret ref
          env:
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
          volumeMounts:
            - name: private-secret-volume
              readOnly: true
              # mount path in container
              mountPath: "/etc/private-key.key"
              # defined in volumes
              subPath: privatekey.key
          readinessProbe:
            httpGet:
              path: /manage/info
              # use named port, same with pod:ports:name
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /manage/healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service-svc
  namespace: springboot-kube
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: consumer-service
    version: V1.0.0
  sessionAffinity: None
  type: ClusterIP